[build-system]
requires = ["hatchling", "skills-runner"]
build-backend = "hatchling.build"

[project]
name = "weather-skills"
version = "0.1.0"
requires-python = ">=3.12,<3.13"
dynamic = ["dependencies", "scripts"]

[tool.hatch.metadata.hooks.skills-runner]
cli = "weather-skills"

[tool.hatch.build.hooks.skills-runner]

[dependency-groups]
dev = [
    "skills-runner"
]

[tool.uv.sources]
skills-runner = { git = "https://github.com/tescalada/skills-runner" }

[tool.pytest.ini_options]

[tool.ruff]
line-length = 100
target-version = "py312"

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F", "I", "B", "UP"]
